<?php

/**
 * @file
 * Contains ckeditor_custom_buttons.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_custom_buttons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor_custom_buttons':
      $output = '';
      $output .= '<h3>' . t('CKEditor Custom Buttons') . '</h3>';
      $output .= '<p>' . t('This module creates custom buttons in the CKEditor toolbar.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('', [':text-formats' => \Drupal::url('filter.admin_overview')]) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}